-- Superseded by the 20260720 schema rewrite (UUIDv7, denormalized counters,
-- partitioned tables, feed_items, post_events). See migrations/20260720000000_*.
-- Kept as a no-op so sqlx's migration history stays linear; DB is being wiped.
